sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t denisaguilar/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true denisaguilar/react-test npm test

after_success:
  - docker build -t denisaguilar/multi-client ./client
  - docker build -t denisaguilar/multi-nginx ./nginx
  - docker build -t denisaguilar/multi-server ./server
  - docker build -t denisaguilar/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Send images to docker hub
  - docker push denisaguilar/multi-client
  - docker push denisaguilar/multi-nginx
  - docker push denisaguilar/multi-server
  - docker push denisaguilar/multi-worker
